../vcpkg/vcpkg/bootstrap-vcpkg.sh
../vcpkg/vcpkg install lib3mf --triplet=wasm32-emscripten --allow-unsupported
cmake .. \
  -DVCPKG_TARGET_TRIPLET=wasm32-emscripten \
  -DCMAKE_C_COMPILER=$(which emcc) \
  -DCMAKE_CXX_COMPILER=$(which em++) \
  -DCMAKE_CXX_COMPILER_WORKS=TRUE \
  -DCMAKE_C_COMPILER_WORKS=TRUE \
  -DCMAKE_CXX_FLAGS="-s MODULARIZE=1 -s EXPORT_ES6=1 -s EXPORTED_RUNTIME_METHODS=FS,ccall,cwrap -s EXCEPTION_CATCHING_ALLOWED=['Lib3MF::ELib3MFException'] -s NO_DISABLE_EXCEPTION_CATCHING=1 -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1" \
  -DCMAKE_C_FLAGS="-s MODULARIZE=1 -s EXPORT_ES6=1 -s EXPORTED_RUNTIME_METHODS=FS,ccall,cwrap -s EXCEPTION_CATCHING_ALLOWED=['Lib3MF::ELib3MFException'] -s NO_DISABLE_EXCEPTION_CATCHING=1 -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1" \
  -DCMAKE_EXE_LINKER_FLAGS="-s MODULARIZE=1 -s EXPORT_ES6=1 -s EXPORTED_RUNTIME_METHODS=FS,ccall,cwrap -s EXCEPTION_CATCHING_ALLOWED=['Lib3MF::ELib3MFException'] -s NO_DISABLE_EXCEPTION_CATCHING=1 -s ASSERTIONS=1 -s ALLOW_MEMORY_GROWTH=1"
make -j 4